default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_development
  username: <%= ENV['APP_USERNAME'] %>
  password: <%= ENV['APP_PASSWORD'] %>
  port: 5432
  host: localhost

test:
  <<: *default
  database: recipe_app_test
  username: <%= ENV['TEST_APP_USERNAME'] %>
  password: <%= ENV['TEST_APP_PASSWORD'] %>
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: Recipe_App_production
  username: Recipe_App
  # password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>
  password: <%= ENV["PGPASSWORD"] %>
